CREATE TABLE books (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    book_title VARCHAR(255) NOT NULL,
    book_sub_title VARCHAR(255),
    book_classification_number VARCHAR(255) NULL,
    book_isbn_number VARCHAR(255),
    book_category ENUM('UMUM', 'FILSAFAT', 'ILMU PENGETAHUAN MASYARAKAT', 'BAHASA', 'MATEMATIKA', 'ILMU PENGETAHUAN TERAPAN', 'KESENIAN', 'LITERATUR', 'SEJARAH'),
    book_publisher VARCHAR(255),
    book_publish_place VARCHAR(255),
    book_publish_date DATE,
    book_author VARCHAR(255),
    book_illustration TINYINT(1),
    book_width TINYINT,
    book_height TINYINT,
    book_page INT,
    book_cover_uri TEXT,
    book_file_uri TEXT,
    book_description TEXT,
    book_language ENUM('INDONESIA','INGGRIS')
);

INSERT INTO books (
    book_title,
    book_sub_title,
    book_classification_number,
    book_isbn_number,
    book_category,
    book_publisher,
    book_publish_place,
    book_publish_year,
    book_author,
    book_illustration,
    book_width_size,
    book_height_size,
    book_page,
    book_cover_uri,
    book_file_uri,
    book_description,
    book_language
) VALUES
('Homo Deus', 'Masa Depan Umat Manusia', '603', '1234567890', 'FILSAFAT', 'Gramedia', 'Banjarbaru', '2012', 'Yuval Noah Harari', 1, 15, 20, 150, null, null, null, 'INDOENSIA'),
('Homo Sapiens', 'Riwayat Singkat Umat Manusia', '604', '123456789', 'SEJARAH', 'Gramedia', 'Martapura', '2015', 'Yuval Noah Harari', 1, 15, 20, 150, null, null, null, 'INDOENSIA'),
('How to be a Brilliant Thinker', 'Latih pikiran Anda dan temnukan solusi-solusi kreatif', '605', '12345678', 'ILMU PENGETAHUAN MASYARAKAT', 'Gramedia', 'Banjarmasin', '2011', 'Paul Sloane', 0, 15, 20, 150, null, null, null, 'INDOENSIA'),
('Sebuah Seni Untuk Bersikap Bodo Amat', 'Pendekatan yang Waras Demi Menjalani Hidup yang Baik', '606', '12345', 'ILMU PENGETAHUAN MASYARAKAT', 'Gramedia', 'Banjarbaru', '2021', 'Mark Manson', 1, 15, 20, 150, null, null, null, 'INDOENSIA'),
('Evolusi', 'Dari Teori ke Fakta', '607', '234567890', 'ILMU PENGETAHUAN TERAPAN', 'Gramedia', 'Banjarbaru', '2010', 'Ernst Mayr', 1, 15, 20, 150, null, null, null, 'INDOENSIA'),
('Madilog', 'Materialisme, Dialektika, dan Logika', '608', '12347890', 'FILSAFAT', 'Gramedia', 'Banyuwangi', '1996', 'Tan Malaka', 1, 15, 20, 150, null, null, null, 'INDOENSIA');